In [1]:
import numpy as np

In [2]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)
print(data)

[[83 74 23 91 19]
 [79 32 49 89 68]
 [18 15 81 80 25]
 [82 96 61  6 12]
 [17 64 84 38 51]]


In [7]:
#1 

data[[1, 3]] = data[[3, 1]]
print(data)

[[83 74 23 91 19]
 [82 96 61  6 12]
 [18 15 81 80 84]
 [79 32 49 89 68]
 [17 64 84 38 51]]


In [9]:
#2

normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized_data)

[[0.85555556 0.75555556 0.18888889 0.94444444 0.14444444]
 [0.84444444 1.         0.61111111 0.         0.06666667]
 [0.13333333 0.1        0.83333333 0.82222222 0.86666667]
 [0.81111111 0.28888889 0.47777778 0.92222222 0.68888889]
 [0.12222222 0.64444444 0.86666667 0.35555556 0.5       ]]


In [10]:
#3

z_score_data = (data - np.mean(data)) / np.std(data)
print(z_score_data)

[[ 0.92213908  0.61657016 -1.11498701  1.19375589 -1.25079542]
 [ 0.88818697  1.36351639  0.17519284 -1.69217274 -1.48846013]
 [-1.28474752 -1.38660382  0.85423487  0.82028277  0.95609118]
 [ 0.78633067 -0.8094181  -0.23223237  1.12585168  0.41285755]
 [-1.31869962  0.27704915  0.95609118 -0.60570549 -0.16432817]]


In [12]:
#4

split_arrays = np.split(np.ravel(data), 5)   # np.ravel = function in NumPy that returns a flattened array (1D) containing all the elements of the input array
                                             # "5" = specifies the number of equally-sized sub-arrays to create
print(split_arrays)

[array([83, 74, 23, 91, 19]), array([82, 96, 61,  6, 12]), array([18, 15, 81, 80, 84]), array([79, 32, 49, 89, 68]), array([17, 64, 84, 38, 51])]


In [14]:
#5
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([2, 3, 4, 5, 6])
dot_product = np.dot(vector1, vector2)
print(dot_product)

70


In [20]:
#6
data2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_multiplication = np.dot(data[:3, :3], data2) #[:3, :3] = selects 3 rows and 3 cols in order to make matrix mult. possible
print(matrix_multiplication)

[[ 540  720  900]
 [ 893 1132 1371]
 [ 645  759  873]]


In [28]:
#stam
data3 = np.array(np.random.randint(1, 100, size=15)).reshape(5,3)
print("data3:\n", data3)
data4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("data4:\n", data4)
matrix_multiplication2 = np.dot(data3, data4)
print("result:\n", matrix_multiplication2)

data3:
 [[59 21  9]
 [60 80 30]
 [97  1 19]
 [ 2 37 71]
 [57 87 42]]
data4:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
result:
 [[ 206  295  384]
 [ 590  760  930]
 [ 234  351  468]
 [ 647  757  867]
 [ 699  885 1071]]


In [33]:
#7

identity_matrix = np.eye(3) * 2 # .eye = generates id matrix
print("identity matrix:\n", identity_matrix)
inverse_matrix = np.linalg.inv(identity_matrix)
print("result:\n", inverse_matrix)

identity matrix:
 [[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
result:
 [[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


In [35]:
#8

eigenvalues, eigenvectors = np.linalg.eig(data[:3, :3])
print(eigenvalues, eigenvectors)

[181.4238077  12.2853833  66.290809 ] [[-0.6185732  -0.72878807 -0.5619531 ]
 [-0.75330164  0.68346772 -0.12714864]
 [-0.22339167  0.0417112   0.81733832]]


In [39]:
#9

data_with_nans = data.astype(float).copy()
indices_of_nans = np.random.choice(5, 5), np.random.choice(5, 5)
data_with_nans[indices_of_nans] = np.nan
print(data_with_nans)

[[83. nan 23. 91. 19.]
 [82. 96. 61. nan 12.]
 [18. 15. nan 80. 84.]
 [79. 32. 49. 89. 68.]
 [17. 64. 84. nan 51.]]


In [40]:
#10

mean_value = np.nanmean(data_with_nans)
data_with_nans[np.isnan(data_with_nans)] = mean_value
print(data_with_nans)

[[83. 57. 23. 91. 19.]
 [82. 96. 61. 57. 12.]
 [18. 15. 57. 80. 84.]
 [79. 32. 49. 89. 68.]
 [17. 64. 84. 57. 51.]]
