In [1]:
#1
import numpy as np

In [3]:
#2
zero_vector = np.zeros(10)  # first define the variable
print(zero_vector)          # then print it

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#3
memory_size = zero_vector.size * zero_vector.itemsize # .size =  total number of elements in the NumPy array ( = 10 )
print(memory_size)                                    # .itemsize = how many bytes each element of the array is occupying
                                                      # multiply size * itemsize = size in bytes of array

80


In [5]:
#4
# python -c 'import numpy; help(numpy.add)

In [6]:
#5
vector_10_to_49 = np.arange(10, 50) # 50 is not inclueded in the .arange
print(vector_10_to_49)              # bc the obj is to get to num 49

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
#6
reversed_vector = vector_10_to_49[::-1]  # [::-1] --> is the slicing notation used to reverse the elements of the array
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [8]:
#7
matrix_3x3 = np.arange(9).reshape(3, 3) # .arange(9) = 9 --> not inclusive
print(matrix_3x3)                       # .reshape = row x cols

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
#8
non_zero_indices = np.nonzero([1, 2, 0, 0, 4, 0]) # finds the indices of the elements that are not 0 inthe array
print(non_zero_indices)

(array([0, 1, 4], dtype=int64),)


In [13]:
#9
identity_matrix = np.eye(3) # function is used to create a 2D identity matrix
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
#10
matrix_5x5 = np.tile(np.arange(5), (5, 1))   # np.tile(range of array), (num times to repeat array - rows, repeat array - cols)
print(matrix_5x5)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [32]:
#11
vector_0_to_1_excluded = np.linspace(0.1, 0.9, 10)
print(vector_0_to_1_excluded)

[0.1        0.18888889 0.27777778 0.36666667 0.45555556 0.54444444
 0.63333333 0.72222222 0.81111111 0.9       ]


In [33]:
#12
random_vector = np.random.rand(10) # .rand = specifies the number of random numbers to generate
sorted_vector = np.sort(random_vector)
print(sorted_vector)

[0.01077867 0.3621515  0.45777699 0.50540077 0.66031475 0.73409153
 0.74067911 0.76039788 0.935657   0.98681803]


In [36]:
#stam
sorted_vector_grid = sorted_vector.reshape(5, 2)
print(sorted_vector_grid)

[[0.01077867 0.3621515 ]
 [0.45777699 0.50540077]
 [0.66031475 0.73409153]
 [0.74067911 0.76039788]
 [0.935657   0.98681803]]


In [37]:
#13
print(np.iinfo(np.int8))
print(np.iinfo(np.int32))
print(np.iinfo(np.int64))
print(np.finfo(np.float32))
print(np.finfo(np.float64))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.40129

In [40]:
#14
float_array = np.random.rand(5).astype(np.float32)
int_array = float_array.astype(np.int32)
print(int_array)

[0 0 0 0 0]


In [43]:
#15
matrix = np.random.rand(3, 3)
mean_subtracted_matrix = matrix - np.mean(matrix, axis=1, keepdims=True)
print(mean_subtracted_matrix)

[[-0.23048477 -0.04223475  0.27271952]
 [ 0.2039774   0.12916942 -0.33314683]
 [ 0.06244238  0.07672964 -0.13917202]]


In [44]:
#16
array_to_sort = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
sorted_array = array_to_sort[array_to_sort[:, 1].argsort()] # [:, 1] means selecting all rows (:) in the second column (1).
print(sorted_array)                                         # argsort() - this returns the indices that would sort the values in the second column in ascending order

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
#17
array_to_swap = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_to_swap[[0, 1]] = array_to_swap[[1, 0]               # array_to_swap[[0, 1]]: extracts the rows w/ indices 0 and 1
print(array_to_swap)             # = array_to_swap[[1, 0]]: replaces the rows w/ indices 0 and 1 w/ the rows w/ indices 1 and 0

[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [47]:
C = np.array([2, 3, 1])
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 0 1 1 1 2]
